---
- name: Node_exporter agent
  hosts: all
  become: yes
  ignore_errors: yes
  tasks:
    - name: Copy Node_exporter
      copy:
        src: /root/node_exporter-1.8.0.linux-amd64
        dest: /tmp/

    - name: Install Node_expoter 
      script: /root/node_exporter.sh

    - name: node_exporter status
      ansible.builtin.systemd:
        name: node_exporter
        state: started
      register: node_exporter_status

    - name: Debug node_exporter status
      ansible.builtin.debug:
        msg: "Node_exporter is {{ 'running' if node_exporter_status.changed else 'not running' }} on {{ ansible_hostname }}"

    - name: Record hostname if node_exporter is running
      ansible.builtin.lineinfile:
        path: /root/node_exporter_installed
        line: "{{ ansible_default_ipv4.address }}"
        create: yes
      delegate_to: localhost
      when: node_exporter_status.changed
   
    - name: Add scrape configuration to prometheus.yml
      ansible.builtin.lineinfile:
        path: /etc/prometheus/prometheus.yml  # Replace with the path to your prometheus.yml file
        line: "  - job_name: \"{{ ansible_hostname }}\"\n    static_configs:\n      - targets: ['{{ ansible_default_ipv4.address }}:9100']"
        insertafter: EOF
      delegate_to: localhost

    - name: Restart prometheus service
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
      delegate_to: localhost
